# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- QA

pool:
  vmImage: 'ubuntu-latest'
variables:
  containerRegistry: 'qaacrpocrandd.azurecr.io'
  imageRepository: 'pocrandd'
  tag: $(Build.BuildNumber)

jobs:
- job: build
  steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'qaacrpocrandd'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: 'src/Dockerfile'
        tags: '$(tag)'

    - publish: manifests
      artifact: manifests
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'qaakspocrandd-default-admin'
        command: 'apply'
        arguments: '-f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.35.0/deploy/static/provider/cloud/deploy.yaml'
- job: deployingress
  steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'qaakspocrandd-default-admin'
        command: 'apply'
        arguments: '-f $(Pipeline.Workspace)/manifests/ingress-rules.yml'

- deployment: Deploy
  displayName: Deploy
  dependsOn: build
  environment: 'qaakspocrandd.default'
  strategy:
    runOnce:
      deploy:
        steps:
          - task: KubernetesManifest@0
            displayName: Deploy to kubernetes cluster
            inputs:
              action: 'deploy'
              manifests: '$(Pipeline.Workspace)/manifests/pocrandd.yml'
              containers: '$(containerRegistry)/$(imageRepository):$(tag)'
