# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release

variables:
  buildId: uat-$(Build.BuildNumber)
  buildConfiguration: 'Release'
  containerRegistry: 'uatacrpocrandd.azurecr.io'
  imageRepository: 'pocrandd'
  tag: $(Build.BuildNumber)
  aksConnection: 'uatakspocrandd-default-admin'
  azConnection: 'dosppocrandd'
  aksName: 'uatakspocrandd'
  rgpName: 'uatrgppocrandd'
jobs:
- job: CR
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'uatacrpocrandd'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: 'src/Dockerfile'
        tags: '$(tag)'

    - publish: manifests
      artifact: manifests

- deployment: Service
  pool:
    vmImage: 'ubuntu-latest'
  displayName: Service
  dependsOn: CR
  environment: 'uatakspocrandd.default'
  strategy:
    runOnce:
      deploy:
        steps:
          - task: KubernetesManifest@0
            displayName: Deploy to kubernetes cluster
            inputs:
              action: 'deploy'
              manifests: '$(Pipeline.Workspace)/manifests/uat-pocrandd.yml'
              containers: '$(containerRegistry)/$(imageRepository):$(tag)'
- job: Ingress
  dependsOn: Service
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Kubernetes@1
    displayName: 'Ingress Controller'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: $(aksConnection)
      command: 'apply'
      arguments: '-f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.35.0/deploy/static/provider/cloud/deploy.yaml'
      outputFormat: 'none'
  - task: Kubernetes@1
    displayName: 'Ingress Rules'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: $(aksConnection)
      command: 'apply'
      arguments: '-f manifests/ingress-rules.yml'
      outputFormat: 'none'
  - task: AzureCLI@1
    displayName: Wait for IP
    inputs:
      azureSubscription: '$(azConnection)'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az aks get-credentials -g $(rgpName) -n $(aksName)
        kubectl get all
        while true
        do
          IP=$(kubectl get ingress ingress-rules -o=jsonpath=''{@.status.loadBalancer.ingress[0].ip}'')
          echo $IP
          if [ -n $IP ]; then
            echo "Ingress ip is $IP"
            break
          else
            echo "Got $IP :( Not done yet..."
          fi
          sleep 5
        done

  - task: Kubernetes@1
    name: GetIngressIp
    displayName: 'Get Ingress IP'
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: $(aksConnection)
      namespace: 'default'
      command: 'get'
      arguments: 'ingress ingress-rules -o=jsonpath=''{@.status.loadBalancer.ingress[0].ip}'''
      outputFormat: 'none'


  - bash: echo '##vso[task.setvariable variable=ip;isOutput=true]$(GetIngressIp.KubectlOutput)'
    name: IngressIp
      
- job: SeleniumTests
  pool:
    vmImage: 'windows-2019'
  dependsOn: 
    - Service
    - Ingress 
  condition: succeeded()
  variables:
    UriAppPocRandD: $[format('http://{0}/', dependencies.Ingress.outputs['IngressIp.ip'])]
  steps:
  - script: dotnet build src --configuration $(buildConfiguration)
    displayName: 'Build Tests Project'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'src/PocRandD.SeleniumTest/PocRandD.SeleniumTest.csproj'
    displayName: 'FunctionalTests'
  - task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact Selenium Results'    

- job: JMeterTests
  pool:
    vmImage: ubuntu-latest
  dependsOn: 
    - SeleniumTests
    - Ingress
  variables:
    hostJMeter: dependencies.Ingress.outputs['IngressIp.ip']
  steps:
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: $(azConnection)
        KeyVaultName: 'keyvaultpocdevops'
        SecretsFilter: 'SasContenedorReportesJMeterB64'
        RunAsPreJob: true
      displayName: 'Obtener SAS para reportes JMeter'
    - task: Bash@3
      displayName: Execute JMeter tests
      inputs:
        targetType: filePath
        filePath: 'jmeter/test.sh'
        arguments: '$PWD jmeterpocrandd.jmx $(hostJMeter) $(buildId)'
        workingDirectory: jmeter
        failOnStderr: false
      env:
          SAS_CONTENEDOR_REPORTESB64: $(SasContenedorReportesJMeterB64)
