trigger:
- UAT/infra
variables:
  azureSubscription: 'dosppocrandd'
  region: 'southcentralus'
  environment: 'uat'
  project: 'pocrandd6'
pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'ps'
    scriptLocation: 'scriptPath'
    scriptPath: 'infra/infrapocrandd.ps1'
    arguments: '$(environment) $(project) $(region)'